name: Dev Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test ./NspStore/NspStore.sln --no-build --verbosity normal

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: llmurd0kll
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: ./NspStore
          file: ./NspStore/Dockerfile
          push: true
          tags: ghcr.io/llmurd0kll/nspstore:dev-${{ github.sha }}
