name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]   # запускается при пуше в main
  workflow_dispatch:       # возможность запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # нужно для пуша в GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./NspStore              # корень репозитория
          file: ./NspStore/Dockerfile     
          push: true
          tags: ghcr.io/llmurd0kll/nspstore:latest
